version: "3.2"
services:
  forpdi-database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: platfor
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: plataformafor
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - platfor-net


  forpdi-backend:
	build:
      context: .
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - platfor-net

  forpdi-frontend:
    build: ../frontend
    image: platfor-front
    depends_on:
      - forpdi-backend
    ports:
      - 81:80  

networks:
  platfor-net:
    driver: bridge
